### ISSUE TITLE
why couldn't names be public?

### ISSUE THREAD

**Issue by cppljevans** [flaub/boost-enum#1]
The line:

https://github.com/flaub/boost-enum/blob/master/libs/test/enum.cpp#L67

declares names as private.  Why couldn't it be public?  This would allow
easy conversion of enum -> string.

**Comment by flaub** [comment]
Take a look at its base class, enum_base<T>:

https://github.com/flaub/boost-enum/blob/master/boost/enum/base.hpp#L69

**Comment by cppljevans** [comment]
Ah.  Good point.  So, in the following code:
//{===============
#include <boost/enum.hpp>

BOOST_ENUM(tests,
 (test1)
 (test2)
)
#include <iostream>
  std::ostream&
operator<<
  ( std::ostream& os
  , tests::domain a_test
  )
  {
  #if 0
    return os<<tests(a_test).str();
  #else
    return os<<tests::names(a_test);
  #endif
  }  
int main()
{
  std::cout<<tests::test1<<"\n";
  return 0;
}
//}===============
instead of directly calling the static names (as in the
#else part of the #if in operator<<), a temporary test is
created and then the member function, str, is called
(as in the then part of the #if in operator<<).

But why got to the trouble of creating a temporary
test when all that's desired is to get the name of
enumerator.  It seems a needless restriction.

-regards,
Larry
